site_name: Traxsense User Manual

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Traxsense: index.md
  - Getting Started:
      - "Quick Start": gettingStarted.md
      - "Book a Demo": bookDemo.md
      - "Recruitment": recruitment.md
  - User Manual:
      - "Logging In/Out": user_manual/loggingInOut.md
      - "Dashboard": user_manual/dashboard.md
      - "Item Tracking": user_manual/itemTracking.md
      - "Alerts": user_manual/alerts.md
      - "Incidents": user_manual/incidents.md
      - "Locations": user_manual/locations.md
      - "Geofence": user_manual/geofence.md
      - "Items": user_manual/items.md
      - "Actions": user_manual/actions.md
      - "Devices": user_manual/devices.md
      - "Types": user_manual/types.md
      - "Tasks": user_manual/tasks.md
      #- "Task Types": user_manual/taskTypes.md
      - "Vehicles": user_manual/vehicles.md
      - "Sensors": user_manual/sensors.md
      - "Routes": user_manual/routes.md
      - "Vehicle Routes": user_manual/vehicleRoutes.md
      - "Reports": user_manual/reports.md
      - "Users": user_manual/users.md
      - "Roles": user_manual/roles.md
      - "Permissions": user_manual/permissions.md
      - "Administration": user_manual/administration.md
      - "Organizations": user_manual/organizations.md
      - "EventBridge": user_manual/eventBridge.md
      - "Flows": user_manual/flows.md
      - "Flow Types": user_manual/flowTypes.md
      - "Rule Engine": user_manual/ruleEngine.md
      - "Updates": user_manual/updates.md
  - Updates:
      - "Releases" : Releases/Overview.md
      - "Release_1.0.6848" : Releases/Release_1.0.6848.md
      - "Release_1.0.6623" : Releases/Release_1.0.6623.md
      - "Release_1.0.6549" : Releases/Release_1.0.6549.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
